### ISSUE TITLE
DS3231RTC broken link for ino file

### ISSUE THREAD

**Issue by goephs** [kriswiner/DS3231RTC#1]
There is a broken link to kriswiner/DS3231RTC ino file .
https://github.com/kriswiner/DS3231RTC/blob/master/DS3231RTCBasicExample.ino

**Comment by kriswiner** [comment]
Which one?

**Comment by goephs** [comment]
Now the url is working to the ino basic example.  Before I was getting error 500.  You can close this. Thank you.
